import { SnakeArchetype } from '../types';

export interface ArchetypeAbilityDef {
  archetype: SnakeArchetype;
  name: string;
  icon: string;
  badge: string;
  themeColor: string;
  glowColor: string;
  // Active Ability
  activeName: string;
  activeDesc: string;
  activeCooldown: number; // in seconds (12s - 22s)
  activeDuration: number; // in seconds (3s - 5s)
  // Passive Ability
  passiveName: string;
  passiveDesc: string;
  // Lv.2 Style Upgrade details
  lv2Title: string;
  lv2Desc: string;
  lv2AuraName: string;
}

export const ARCHETYPE_ABILITIES: Record<SnakeArchetype, ArchetypeAbilityDef> = {
  angel: {
    archetype: 'angel',
    name: 'Seraphim Angel',
    icon: '🪽',
    badge: 'DIVINE',
    themeColor: '#facc15',
    glowColor: '#fef08a',
    activeName: 'Divine Shield',
    activeDesc: 'Summons a radiant celestial halo bubble for 3.0s that deflects all incoming bullets.',
    activeCooldown: 18,
    activeDuration: 3.0,
    passiveName: 'Grace',
    passiveDesc: 'Slowly regenerates +3.5 HP/sec when out of combat and not taking damage for 3s.',
    lv2Title: 'Lv.2 Seraphic Ascension',
    lv2Desc: 'Shield duration +0.8s and grace aura pulses faint blinding light.',
    lv2AuraName: 'Holy Starlight Aura',
  },
  devil: {
    archetype: 'devil',
    name: 'Infernal Devil',
    icon: '😈',
    badge: 'DEMON',
    themeColor: '#ef4444',
    glowColor: '#f87171',
    activeName: 'Hellfire Burst',
    activeDesc: 'Unleashes an expanding vortex ring of hellfire around the head, burning nearby enemies.',
    activeCooldown: 16,
    activeDuration: 3.2,
    passiveName: 'Soul Harvest',
    passiveDesc: 'Each kill permanently harvests souls, granting +5% bonus damage per kill for the match.',
    lv2Title: 'Lv.2 Brimstone Awakening',
    lv2Desc: 'Hellfire burst radius expanded by +25% and leaves flaming ground embers.',
    lv2AuraName: 'Hellfire Lava Vents',
  },
  blackhole: {
    archetype: 'blackhole',
    name: 'Black Hole Void',
    icon: '🌌',
    badge: 'COSMIC',
    themeColor: '#a855f7',
    glowColor: '#c084fc',
    activeName: 'Singularity',
    activeDesc: 'Creates a massive gravitational well that vortex-pulls nearby snakes, bots, and pickups.',
    activeCooldown: 20,
    activeDuration: 3.5,
    passiveName: 'Event Horizon',
    passiveDesc: 'Passively devours stray bullets passing within 65px of the head into dark matter.',
    lv2Title: 'Lv.2 Void Anomaly',
    lv2Desc: 'Singularity pull power increased by +35% with distorted gravity ripple VFX.',
    lv2AuraName: 'Gravitational Singularity',
  },
  robot: {
    archetype: 'robot',
    name: 'Robot Titan MK-IV',
    icon: '🤖',
    badge: 'MECHA',
    themeColor: '#38bdf8',
    glowColor: '#7dd3fc',
    activeName: 'Overclock',
    activeDesc: 'Supercharges fire rate (+75%) and boost speed for 4.0s, followed by a brief 1.2s cooling overheat.',
    activeCooldown: 17,
    activeDuration: 4.0,
    passiveName: 'Auto-Repair',
    passiveDesc: 'Internal nanite reactors deliver steady +12 HP armor repair pulses every 4.0 seconds.',
    lv2Title: 'Lv.2 Overclocked Frame',
    lv2Desc: 'Reduces overheat penalty duration by 50% and unleashes electric sparks.',
    lv2AuraName: 'High-Voltage Discharge',
  },
  dragon: {
    archetype: 'dragon',
    name: 'Emerald Dragon',
    icon: '🐉',
    badge: 'MYTHIC',
    themeColor: '#10b981',
    glowColor: '#6ee7b7',
    activeName: 'Flame Breath',
    activeDesc: 'Breathes an incandescent cone of dragonfire in front of the head, scorching enemy snakes.',
    activeCooldown: 15,
    activeDuration: 2.8,
    passiveName: 'Scales',
    passiveDesc: 'Reinforced draconic plating absorbs 40% reduced damage from flanking and rear body hits.',
    lv2Title: 'Lv.2 Draconic Fury',
    lv2Desc: 'Increases flame breath range and ignites targets with lingering draconic burn.',
    lv2AuraName: 'Dragonfire Flare',
  },
  cyber: {
    archetype: 'cyber',
    name: 'Cyber Viper',
    icon: '⚡',
    badge: 'CYBER',
    themeColor: '#06b6d4',
    glowColor: '#67e8f9',
    activeName: 'Glitch Dash',
    activeDesc: 'Instant quantum phase-dash teleport forward that leaves a holographic decoy afterimage.',
    activeCooldown: 14,
    activeDuration: 1.8,
    passiveName: 'Hack',
    passiveDesc: 'When hit, 35% chance to disrupt & jam the attacker’s weapon system for 2.5 seconds.',
    lv2Title: 'Lv.2 Matrix Infiltration',
    lv2Desc: 'Glitch dash leaves an EMP shockwave that briefly slows nearby enemies.',
    lv2AuraName: 'Matrix Optical Camo',
  },
  phoenix: {
    archetype: 'phoenix',
    name: 'Solar Phoenix',
    icon: '🔥',
    badge: 'REBIRTH',
    themeColor: '#f97316',
    glowColor: '#fbbf24',
    activeName: 'Solar Flare Burst',
    activeDesc: 'Triggers a superheated fiery burst outward, pushing away enemies and incinerating projectiles.',
    activeCooldown: 18,
    activeDuration: 3.0,
    passiveName: 'Fire Trail & Rebirth',
    passiveDesc: 'Leaves a continuous fire trail that burns enemies, and revives once per match with an explosive burst.',
    lv2Title: 'Lv.2 Eternal Flame',
    lv2Desc: 'Fire trail burns longer and rebirth burst radius is increased by +40%.',
    lv2AuraName: 'Phoenix Flame Wings',
  },
  frost: {
    archetype: 'frost',
    name: 'Glacial Frost',
    icon: '❄️',
    badge: 'CRYO',
    themeColor: '#38bdf8',
    glowColor: '#bae6fd',
    activeName: 'Blizzard Surge',
    activeDesc: 'Unleashes a sub-zero cryo wave freezing all surrounding enemies and bullets in place.',
    activeCooldown: 16,
    activeDuration: 3.5,
    passiveName: 'Ice Trail & Frostbite',
    passiveDesc: 'Leaves an ice trail that slows chasers, and bullets stack a freeze effect slowing targets up to 50%.',
    lv2Title: 'Lv.2 Absolute Zero',
    lv2Desc: 'Ice trail freezes chasers faster and bullet frost stacks max out at 5 stacks.',
    lv2AuraName: 'Crystalline Glaze',
  },
  venom: {
    archetype: 'venom',
    name: 'Toxic Venom',
    icon: '🧪',
    badge: 'TOXIC',
    themeColor: '#84cc16',
    glowColor: '#a3e635',
    activeName: 'Acidic Outburst',
    activeDesc: 'Sprays a noxious pool of neurotoxin around the snake that severely weakens enemy armor.',
    activeCooldown: 15,
    activeDuration: 3.0,
    passiveName: 'Toxic Trail & Poison',
    passiveDesc: 'Poison bullets deal damage over time (DoT), and leaves a toxic trail that damages trailing enemies.',
    lv2Title: 'Lv.2 Bio-Hazard Plating',
    lv2Desc: 'Poison duration increased by 2s and toxic trail deals +35% damage.',
    lv2AuraName: 'Neurotoxin Miasma',
  },
  storm: {
    archetype: 'storm',
    name: 'Thunder Storm',
    icon: '⚡',
    badge: 'VOLT',
    themeColor: '#3b82f6',
    glowColor: '#60a5fa',
    activeName: 'Overcharge Discharge',
    activeDesc: 'Unleashes a violent tempest of fork lightning jumping between all nearby enemies.',
    activeCooldown: 17,
    activeDuration: 3.0,
    passiveName: 'Chain Lightning & Static Shock',
    passiveDesc: 'Bullets arc chain lightning to jump between nearby enemies, and boosting creates a static shock pulse.',
    lv2Title: 'Lv.2 Supercell Surge',
    lv2Desc: 'Chain lightning jumps to 3 targets and static shock radius increased.',
    lv2AuraName: 'Plasma Arc Generator',
  },
  phantom: {
    archetype: 'phantom',
    name: 'Shadow Phantom',
    icon: '👻',
    badge: 'PHASE',
    themeColor: '#818cf8',
    glowColor: '#c7d2fe',
    activeName: 'Phase Shift',
    activeDesc: 'Goes translucent and phases through solid map obstacles and barriers for 4.5 seconds.',
    activeCooldown: 16,
    activeDuration: 4.5,
    passiveName: 'Ethereal Weave',
    passiveDesc: 'While phasing, takes 60% reduced damage from bullets and moves +20% faster.',
    lv2Title: 'Lv.2 Spectral Transcendence',
    lv2Desc: 'Phase duration +1s and leaves spectral rift particles that confuse bots.',
    lv2AuraName: 'Spectral Rift Cloak',
  },
  vampire: {
    archetype: 'vampire',
    name: 'Crimson Vampire',
    icon: '🦇',
    badge: 'BLOOD',
    themeColor: '#b91c1c',
    glowColor: '#f87171',
    activeName: 'Blood Frenzy',
    activeDesc: 'Dashes forward with +45% speed, siphoning life from all hits for 4.0 seconds.',
    activeCooldown: 18,
    activeDuration: 4.0,
    passiveName: 'Lifesteal & Bat Swarm',
    passiveDesc: 'Lifesteal on kills restoring 40% HP, accompanied by a signature bat-swarm death effect.',
    lv2Title: 'Lv.2 Vampire Lord',
    lv2Desc: 'Lifesteal on kills increased to 50% HP and grants temporary shield overcharge.',
    lv2AuraName: 'Crimson Blood Mist',
  },
  chrono: {
    archetype: 'chrono',
    name: 'Temporal Chrono',
    icon: '⏳',
    badge: 'TIME',
    themeColor: '#d97706',
    glowColor: '#fde68a',
    activeName: 'Time Dilation',
    activeDesc: 'Creates a localized time-slow bubble around itself with rotating clock-gear visuals, slowing enemies 65%.',
    activeCooldown: 19,
    activeDuration: 4.5,
    passiveName: 'Chronometer',
    passiveDesc: 'Slows incoming enemy projectiles passing through the time bubble by 75%.',
    lv2Title: 'Lv.2 Paradox Core',
    lv2Desc: 'Expands time bubble radius to 280px and increases slow intensity.',
    lv2AuraName: 'Clockwork Gears Field',
  },
  ninja: {
    archetype: 'ninja',
    name: 'Shadow Ninja',
    icon: '🥷',
    badge: 'SHADOW',
    themeColor: '#18181b',
    glowColor: '#71717a',
    activeName: 'Smoke Bomb Escape',
    activeDesc: 'Detonates a smoke bomb, turning invisible for 3.0s and dashing forward to escape danger.',
    activeCooldown: 14,
    activeDuration: 3.0,
    passiveName: 'Dash-Slash Melee',
    passiveDesc: 'Wields a dash-slash melee attack instead of a gun, dealing devastating blade cleave damage in close quarters.',
    lv2Title: 'Lv.2 Shinobi Mastery',
    lv2Desc: 'Dash-slash melee damage +35% and smoke bomb leaves blinding smoke screen.',
    lv2AuraName: 'Shadow Katana Gleam',
  },
  crystal: {
    archetype: 'crystal',
    name: 'Prismatic Crystal',
    icon: '💎',
    badge: 'TANK',
    themeColor: '#06b6d4',
    glowColor: '#a5f3fc',
    activeName: 'Prismatic Reflection',
    activeDesc: 'Polishes crystal facets into a 100% reflective mirror for 3.5s, bouncing back all incoming bullets.',
    activeCooldown: 17,
    activeDuration: 3.5,
    passiveName: 'Crystal Tank Carapace',
    passiveDesc: 'High-armor tank with +60% HP that is slightly slower (-12% speed) but passively reflects 40% of bullets.',
    lv2Title: 'Lv.2 Diamond Hardness',
    lv2Desc: 'Base armor +20% and reflected bullets deal +25% bonus damage.',
    lv2AuraName: 'Prismatic Refraction Gleam',
  },
  alien: {
    archetype: 'alien',
    name: 'Xenomorph Alien',
    icon: '👽',
    badge: 'BIO',
    themeColor: '#10b981',
    glowColor: '#6ee7b7',
    activeName: 'Corrosive Acid Nova',
    activeDesc: 'Spews an 8-way burst of glowing corrosive acid that instantly dissolves and melts shields.',
    activeCooldown: 15,
    activeDuration: 3.0,
    passiveName: 'Acid Spit & Bio-Luminescence',
    passiveDesc: 'Acid spit attacks melt shields on contact, housed in a pulsating bio-luminescent body.',
    lv2Title: 'Lv.2 Extraterrestrial Hive',
    lv2Desc: 'Acid spit leaves bubbling acid pools that melt armor over time.',
    lv2AuraName: 'Bio-Luminescent Pulse',
  },
};

export function getArchetypeAbility(archetype?: SnakeArchetype): ArchetypeAbilityDef {
  if (!archetype) return ARCHETYPE_ABILITIES.cyber;
  return ARCHETYPE_ABILITIES[archetype] || ARCHETYPE_ABILITIES.cyber;
}
