import { DeathEffectDef, DeathEffectType } from '../types';

export const DEATH_EFFECTS: DeathEffectDef[] = [
  {
    id: 'cyber-matrix',
    name: 'Matrix Decompile',
    price: 0,
    badge: 'DEFAULT',
    description: 'Victim decompiles into a cloud of emerald cybernetic pixels and cascading binary code.',
    primaryColor: '#22c55e',
    secondaryColor: '#15803d',
    icon: 'binary',
    particleCount: 35,
  },
  {
    id: 'neon-skull',
    name: 'Neon Skull Hologram',
    price: 150,
    badge: 'POPULAR',
    description: 'A glowing cyan and magenta cybernetic skull hologram laughs and expands across the arena.',
    primaryColor: '#06b6d4',
    secondaryColor: '#f43f5e',
    icon: 'skull',
    particleCount: 45,
  },
  {
    id: 'golden-cash-storm',
    name: 'Golden Cash Blast',
    price: 250,
    badge: 'LUXURY',
    description: 'Explodes into a glorious hurricane of flying dollar bills, glowing cash symbols, and gold coins.',
    primaryColor: '#eab308',
    secondaryColor: '#f59e0b',
    icon: 'dollar',
    particleCount: 55,
  },
  {
    id: 'plasma-storm',
    name: 'Plasma Overload',
    price: 350,
    badge: 'HIGH-VOLT',
    description: 'Catastrophic electric ionization sending jagged violet lightning bolts and plasma sparks in all directions.',
    primaryColor: '#a855f7',
    secondaryColor: '#ec4899',
    icon: 'lightning',
    particleCount: 50,
  },
  {
    id: 'nuclear-supernova',
    name: 'Nuclear Supernova',
    price: 450,
    badge: 'DEVASTATING',
    description: 'Colossal blinding atomic shockwave followed by expanding incendiary rings and nuclear fallout.',
    primaryColor: '#f97316',
    secondaryColor: '#ef4444',
    icon: 'nuclear',
    particleCount: 65,
  },
  {
    id: 'void-singularity',
    name: 'Void Singularity',
    price: 600,
    badge: 'LEGENDARY',
    description: 'A miniature gravitational black hole collapses inward, devouring light before an antimatter rupture.',
    primaryColor: '#8b5cf6',
    secondaryColor: '#1e1b4b',
    icon: 'void',
    particleCount: 60,
  },
  {
    id: 'laser-fireworks',
    name: 'Championship Fireworks',
    price: 750,
    badge: 'MYTHIC',
    description: 'Prismatic rainbow laser bursts and sparkling championship starbursts celebrate your kill.',
    primaryColor: '#38bdf8',
    secondaryColor: '#fbbf24',
    icon: 'star',
    particleCount: 70,
  },
  {
    id: 'bat-swarm',
    name: 'Vampiric Bat Swarm',
    price: 35000,
    badge: 'VAMPIRE',
    description: 'Victim dissolves into a shadowy vortex of fluttering nocturnal bats with piercing scarlet eyes.',
    primaryColor: '#dc2626',
    secondaryColor: '#171717',
    icon: 'bat',
    particleCount: 50,
  },
];

export function getDeathEffectById(id: string): DeathEffectDef {
  return DEATH_EFFECTS.find((e) => e.id === id) || DEATH_EFFECTS[0];
}
