import { SkinDef, SkinRarity, SnakeArchetype } from '../types';

export const RARITY_CONFIG: Record<
  SkinRarity,
  {
    label: string;
    name: string;
    color: string;
    textColor: string;
    bgColor: string;
    borderColor: string;
    glowColor: string;
    dropRate: number; // Percentage
    cashback: number; // Duplicate refund
  }
> = {
  common: {
    label: 'COMMON',
    name: 'Common',
    color: '#94a3b8',
    textColor: 'text-slate-300',
    bgColor: 'bg-slate-900/90',
    borderColor: 'border-slate-500/50',
    glowColor: 'rgba(148, 163, 184, 0.3)',
    dropRate: 40.0,
    cashback: 400,
  },
  uncommon: {
    label: 'UNCOMMON',
    name: 'Uncommon',
    color: '#10b981',
    textColor: 'text-emerald-400',
    bgColor: 'bg-emerald-950/70',
    borderColor: 'border-emerald-500/60',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    dropRate: 28.5,
    cashback: 650,
  },
  epic: {
    label: 'EPIC',
    name: 'Epic',
    color: '#a855f7',
    textColor: 'text-purple-300',
    bgColor: 'bg-purple-950/70',
    borderColor: 'border-purple-500/70',
    glowColor: 'rgba(168, 85, 247, 0.5)',
    dropRate: 18.0,
    cashback: 1200,
  },
  legendary: {
    label: 'LEGENDARY',
    name: 'Legendary',
    color: '#f59e0b',
    textColor: 'text-amber-300',
    bgColor: 'bg-amber-950/70',
    borderColor: 'border-amber-400/80',
    glowColor: 'rgba(245, 158, 11, 0.6)',
    dropRate: 8.5,
    cashback: 2500,
  },
  mythic: {
    label: 'MYTHIC',
    name: 'Mythic',
    color: '#f43f5e',
    textColor: 'text-rose-400',
    bgColor: 'bg-rose-950/80',
    borderColor: 'border-rose-500/90',
    glowColor: 'rgba(244, 63, 94, 0.75)',
    dropRate: 4.2,
    cashback: 5000,
  },
  secret: {
    label: '★ SECRET ★',
    name: 'Secret',
    color: '#ec4899',
    textColor: 'text-pink-300',
    bgColor: 'bg-gradient-to-r from-pink-950/90 via-purple-950/90 to-cyan-950/90',
    borderColor: 'border-pink-400',
    glowColor: 'rgba(236, 72, 153, 0.9)',
    dropRate: 0.8,
    cashback: 12000,
  },
};

export const SKINS: SkinDef[] = [
  // ==========================================
  // 1. ANGEL ARCHETYPE
  // ==========================================
  {
    id: 'angel-acolyte',
    name: 'Acolyte Angel²',
    archetype: 'angel',
    rarity: 'common',
    badge: 'ACOLYTE',
    price: 800,
    primaryColor: '#e2e8f0',
    secondaryColor: '#cbd5e1',
    accentColor: '#94a3b8',
    coreGlow: '#f8fafc',
    eyeColor: '#38bdf8',
    pattern: 'celestial',
    headDetail: 'angel-wings-halo',
    specialAura: 'Fledgling Halo Glow',
    description: 'Initiate celestial guardian equipped with pure silver feathers and a budding sacred halo.',
  },
  {
    id: 'angel-dawn',
    name: 'Dawn Valkyrie²',
    archetype: 'angel',
    rarity: 'uncommon',
    badge: 'VALKYRIE',
    price: 2500,
    primaryColor: '#fef08a',
    secondaryColor: '#facc15',
    accentColor: '#eab308',
    coreGlow: '#ffffff',
    eyeColor: '#0284c7',
    pattern: 'celestial',
    headDetail: 'angel-wings-halo',
    specialAura: 'Morning Sun Glow',
    description: 'Battle-hardened valkyrie winged in morning light, shielding allies from mortal peril.',
  },
  {
    id: 'angel-sentinel',
    name: 'Archangel Sentinel²',
    archetype: 'angel',
    rarity: 'epic',
    badge: 'SENTINEL',
    price: 12000,
    primaryColor: '#0284c7',
    secondaryColor: '#bae6fd',
    accentColor: '#38bdf8',
    coreGlow: '#e0f2fe',
    eyeColor: '#fde047',
    pattern: 'celestial',
    headDetail: 'angel-wings-halo',
    specialAura: 'Azure Holy Light',
    description: 'High sentinel of the upper skies, wielding condensed azure starlight plumage.',
  },
  {
    id: 'angel-seraph',
    name: 'Seraphim Angel²',
    archetype: 'angel',
    rarity: 'legendary',
    badge: 'DIVINE',
    price: 35000,
    primaryColor: '#f8fafc',
    secondaryColor: '#fef08a',
    accentColor: '#eab308',
    coreGlow: '#ffffff',
    eyeColor: '#38bdf8',
    pattern: 'celestial',
    headDetail: 'angel-wings-halo',
    specialAura: 'Holy Starlight Aura',
    description: 'Divine celestial entity crowned with a levitating golden halo and radiant feathered wings.',
  },
  {
    id: 'angel-deva',
    name: 'Ascended Deva²',
    archetype: 'angel',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#ffffff',
    secondaryColor: '#f472b6',
    accentColor: '#fbbf24',
    coreGlow: '#ffffff',
    eyeColor: '#22d3ee',
    pattern: 'celestial',
    headDetail: 'angel-wings-halo',
    specialAura: 'Omnipresent Blessing',
    description: 'Supreme transcendental deity bathed in pearlescent stardust and divine cosmic gold.',
  },
  {
    id: 'angel-secret-cherub',
    name: '★ OMNIPOTENT CHERUB ★',
    archetype: 'angel',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#fff1f2',
    secondaryColor: '#f43f5e',
    accentColor: '#38bdf8',
    coreGlow: '#fb7185',
    eyeColor: '#fbbf24',
    pattern: 'rainbow',
    headDetail: 'angel-wings-halo',
    specialAura: 'Transcendent Prismatic Halo',
    description: 'ULTRA SECRET: The forbidden supreme creator form. Shimmers with hyper-chromatic divine light.',
  },

  // ==========================================
  // 2. DEVIL ARCHETYPE
  // ==========================================
  {
    id: 'devil-imp',
    name: 'Brimstone Imp²',
    archetype: 'devil',
    rarity: 'common',
    badge: 'IMP',
    price: 800,
    primaryColor: '#27272a',
    secondaryColor: '#3f3f46',
    accentColor: '#71717a',
    coreGlow: '#ef4444',
    eyeColor: '#f97316',
    pattern: 'infernal',
    headDetail: 'devil-horns',
    specialAura: 'Smoldering Ash',
    description: 'Scavenger demon from the ash pits, tipped with sharp blackened brimstone horns.',
  },
  {
    id: 'devil-fiend',
    name: 'Underworld Fiend²',
    archetype: 'devil',
    rarity: 'uncommon',
    badge: 'FIEND',
    price: 2500,
    primaryColor: '#581c87',
    secondaryColor: '#3b0764',
    accentColor: '#9333ea',
    coreGlow: '#c084fc',
    eyeColor: '#ef4444',
    pattern: 'infernal',
    headDetail: 'devil-horns',
    specialAura: 'Nether Flame Embers',
    description: 'Shadowy demon infused with abyssal purple hellfire that incinerates prey.',
  },
  {
    id: 'devil-hellgate',
    name: 'Hellgate Ravager²',
    archetype: 'devil',
    rarity: 'epic',
    badge: 'RAVAGER',
    price: 12000,
    primaryColor: '#b91c1c',
    secondaryColor: '#450a0a',
    accentColor: '#f97316',
    coreGlow: '#fca5a5',
    eyeColor: '#fde047',
    pattern: 'infernal',
    headDetail: 'devil-horns',
    specialAura: 'Lava Vent Eruption',
    description: 'Hellfire juggernaut forged in open magma rifts, exhaling molten volcanic ash.',
  },
  {
    id: 'devil-infernal',
    name: 'Infernal Devil²',
    archetype: 'devil',
    rarity: 'legendary',
    badge: 'DEMON',
    price: 35000,
    primaryColor: '#18181b',
    secondaryColor: '#7f1d1d',
    accentColor: '#ef4444',
    coreGlow: '#f97316',
    eyeColor: '#fbbf24',
    pattern: 'infernal',
    headDetail: 'devil-horns',
    specialAura: 'Hellfire Lava Vents',
    description: 'Demonic underworld titan with curved obsidian battle horns, magma fissures, and molten embers.',
  },
  {
    id: 'devil-archdemon',
    name: 'Abyssal Archdemon²',
    archetype: 'devil',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#09090b',
    secondaryColor: '#dc2626',
    accentColor: '#fbbf24',
    coreGlow: '#f87171',
    eyeColor: '#ffffff',
    pattern: 'infernal',
    headDetail: 'devil-horns',
    specialAura: 'Apocalyptic Hellstorm',
    description: 'Ancient dark sovereign commanding legions of the void, burning with thermonuclear hellfire.',
  },
  {
    id: 'devil-secret-lucifer',
    name: '★ LUCIFER MORNINGSTAR ★',
    archetype: 'devil',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#000000',
    secondaryColor: '#e11d48',
    accentColor: '#f43f5e',
    coreGlow: '#fda4af',
    eyeColor: '#38bdf8',
    pattern: 'glitch',
    headDetail: 'devil-horns',
    specialAura: 'Blood Moon Supernova',
    description: 'ULTRA SECRET: The fallen dark king crowned with blood-red plasma crown and dimensional fissures.',
  },

  // ==========================================
  // 3. BLACK HOLE ARCHETYPE
  // ==========================================
  {
    id: 'blackhole-drone',
    name: 'Dark Matter Drone²',
    archetype: 'blackhole',
    rarity: 'common',
    badge: 'VOID',
    price: 800,
    primaryColor: '#1e1b4b',
    secondaryColor: '#0f172a',
    accentColor: '#6366f1',
    coreGlow: '#818cf8',
    eyeColor: '#a5b4fc',
    pattern: 'cosmic_void',
    headDetail: 'singularity-vortex',
    specialAura: 'Minor Gravity Well',
    description: 'Synthesized singularity probe that captures drifting subatomic particles.',
  },
  {
    id: 'blackhole-nebula',
    name: 'Nebula Wanderer²',
    archetype: 'blackhole',
    rarity: 'uncommon',
    badge: 'NEBULA',
    price: 2500,
    primaryColor: '#0c4a6e',
    secondaryColor: '#082f49',
    accentColor: '#38bdf8',
    coreGlow: '#7dd3fc',
    eyeColor: '#38bdf8',
    pattern: 'cosmic_void',
    headDetail: 'singularity-vortex',
    specialAura: 'Stardust Accretion',
    description: 'Wandering cosmic anomaly laced with azure star dust and gravity pulses.',
  },
  {
    id: 'void-stalker',
    name: 'Void Stalker²',
    archetype: 'blackhole',
    rarity: 'epic',
    badge: 'VOID',
    price: 12000,
    primaryColor: '#a855f7',
    secondaryColor: '#6b21a8',
    accentColor: '#c084fc',
    coreGlow: '#e9d5ff',
    eyeColor: '#f472b6',
    pattern: 'stealth',
    headDetail: 'spikes',
    specialAura: 'Dark Matter Flux',
    description: 'Stealth-coated obsidian body with dark matter energy cells that distort sensory radar.',
  },
  {
    id: 'blackhole-void',
    name: 'Black Hole Void²',
    archetype: 'blackhole',
    rarity: 'legendary',
    badge: 'COSMIC',
    price: 35000,
    primaryColor: '#030712',
    secondaryColor: '#2e1065',
    accentColor: '#a855f7',
    coreGlow: '#c084fc',
    eyeColor: '#38bdf8',
    pattern: 'cosmic_void',
    headDetail: 'singularity-vortex',
    specialAura: 'Gravitational Singularity',
    description: 'Cosmic gravitational anomaly that warps space with a swirling event horizon singularity vortex.',
  },
  {
    id: 'blackhole-quasar',
    name: 'Supermassive Quasar²',
    archetype: 'blackhole',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#3b0764',
    secondaryColor: '#09090b',
    accentColor: '#ec4899',
    coreGlow: '#f472b6',
    eyeColor: '#22d3ee',
    pattern: 'cosmic_void',
    headDetail: 'singularity-vortex',
    specialAura: 'Relativistic Gamma Jet',
    description: 'Hyper-luminous galactic core projecting blinding gamma rays across interstellar space.',
  },
  {
    id: 'blackhole-secret-omega',
    name: '★ EVENT HORIZON OMEGA ★',
    archetype: 'blackhole',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#000000',
    secondaryColor: '#581c87',
    accentColor: '#06b6d4',
    coreGlow: '#c084fc',
    eyeColor: '#ffffff',
    pattern: 'glitch',
    headDetail: 'singularity-vortex',
    specialAura: 'Spacetime Collapse Vortex',
    description: 'ULTRA SECRET: The singularity threshold where physics breaks down into glitching matter.',
  },

  // ==========================================
  // 4. ROBOT ARCHETYPE
  // ==========================================
  {
    id: 'robot-scrap',
    name: 'Scrap Mecha Unit²',
    archetype: 'robot',
    rarity: 'common',
    badge: 'SCRAP',
    price: 800,
    primaryColor: '#475569',
    secondaryColor: '#334155',
    accentColor: '#64748b',
    coreGlow: '#94a3b8',
    eyeColor: '#f59e0b',
    pattern: 'mecha',
    headDetail: 'mecha-visor-antennas',
    specialAura: 'Hydraulic Piston Steam',
    description: 'Salvaged industrial frame reinforced with bolted steel plates and hydraulic pistons.',
  },
  {
    id: 'robot-sentry',
    name: 'Cyber Sentry MK-II²',
    archetype: 'robot',
    rarity: 'uncommon',
    badge: 'SENTRY',
    price: 2500,
    primaryColor: '#1e3a8a',
    secondaryColor: '#172554',
    accentColor: '#38bdf8',
    coreGlow: '#60a5fa',
    eyeColor: '#22c55e',
    pattern: 'mecha',
    headDetail: 'mecha-visor-antennas',
    specialAura: 'Radar Scan Wave',
    description: 'Automated perimeter defense unit outfitted with long-range radio telemetry antennas.',
  },
  {
    id: 'golden-mecha',
    name: 'Golden Mecha²',
    archetype: 'robot',
    rarity: 'epic',
    badge: 'PRESTIGE',
    price: 12000,
    primaryColor: '#eab308',
    secondaryColor: '#854d0e',
    accentColor: '#fde047',
    coreGlow: '#fef9c3',
    eyeColor: '#ef4444',
    pattern: 'gold',
    headDetail: 'dual-cannon',
    specialAura: 'Auric Armor Gleam',
    description: 'Elite royal prestige armor forged with reinforced auric alloy and twin cannons.',
  },
  {
    id: 'robot-titan',
    name: 'Robot Titan MK-IV²',
    archetype: 'robot',
    rarity: 'legendary',
    badge: 'MECHA',
    price: 35000,
    primaryColor: '#334155',
    secondaryColor: '#0f172a',
    accentColor: '#0ea5e9',
    coreGlow: '#38bdf8',
    eyeColor: '#ef4444',
    pattern: 'mecha',
    headDetail: 'mecha-visor-antennas',
    specialAura: 'High-Voltage Discharge',
    description: 'Military-grade cybernetic warframe armed with hydraulic comms antennas and sweeping laser visor.',
  },
  {
    id: 'robot-dreadnought',
    name: 'Giga Dreadnought AI²',
    archetype: 'robot',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#020617',
    secondaryColor: '#0f172a',
    accentColor: '#06b6d4',
    coreGlow: '#22d3ee',
    eyeColor: '#ef4444',
    pattern: 'mecha',
    headDetail: 'mecha-visor-antennas',
    specialAura: 'Quantum AI Core',
    description: 'Sentient planetary defense mainframe equipped with infinite overclock hyper-reactors.',
  },
  {
    id: 'robot-secret-zero',
    name: '★ PROJECT ZERO: OVERCLOCK ★',
    archetype: 'robot',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#0f172a',
    secondaryColor: '#06b6d4',
    accentColor: '#e11d48',
    coreGlow: '#f43f5e',
    eyeColor: '#22c55e',
    pattern: 'glitch',
    headDetail: 'mecha-visor-antennas',
    specialAura: 'Nuclear Core Meltdown',
    description: 'ULTRA SECRET: Experimental rogue warframe operating beyond thermal safeguards at 900% power.',
  },

  // ==========================================
  // 5. DRAGON ARCHETYPE
  // ==========================================
  {
    id: 'dragon-forest',
    name: 'Forest Drake²',
    archetype: 'dragon',
    rarity: 'common',
    badge: 'DRAKE',
    price: 800,
    primaryColor: '#166534',
    secondaryColor: '#14532d',
    accentColor: '#22c55e',
    coreGlow: '#86efac',
    eyeColor: '#facc15',
    pattern: 'draconic',
    headDetail: 'dragon-crest',
    specialAura: 'Verdant Scale Sheen',
    description: 'Woodland drake protected by overlapping bark-like reptilian armor and green crest horn.',
  },
  {
    id: 'dragon-mountain',
    name: 'Mountain Wyrm²',
    archetype: 'dragon',
    rarity: 'uncommon',
    badge: 'WYRM',
    price: 2500,
    primaryColor: '#374151',
    secondaryColor: '#1f2937',
    accentColor: '#10b981',
    coreGlow: '#6ee7b7',
    eyeColor: '#fbbf24',
    pattern: 'draconic',
    headDetail: 'dragon-crest',
    specialAura: 'Granite Ridge Armor',
    description: 'Subterranean mountain serpent encrusted with jade ores and impenetrable granite spine.',
  },
  {
    id: 'dragon-obsidian',
    name: 'Obsidian Wyvern²',
    archetype: 'dragon',
    rarity: 'epic',
    badge: 'WYVERN',
    price: 12000,
    primaryColor: '#1c1917',
    secondaryColor: '#44403c',
    accentColor: '#dc2626',
    coreGlow: '#ef4444',
    eyeColor: '#f97316',
    pattern: 'draconic',
    headDetail: 'dragon-crest',
    specialAura: 'Volcanic Scale Hearth',
    description: 'Black volcanic wyvern whose veins pulse with liquid magma beneath glassy obsidian scales.',
  },
  {
    id: 'dragon-wyrm',
    name: 'Emerald Dragon²',
    archetype: 'dragon',
    rarity: 'legendary',
    badge: 'MYTHIC',
    price: 35000,
    primaryColor: '#065f46',
    secondaryColor: '#022c22',
    accentColor: '#10b981',
    coreGlow: '#6ee7b7',
    eyeColor: '#fde047',
    pattern: 'draconic',
    headDetail: 'dragon-crest',
    specialAura: 'Dragonfire Flare',
    description: 'Ancient armored wyrm adorned with swept dragon crest horns and incandescent draconic plating.',
  },
  {
    id: 'dragon-bahamut',
    name: 'Ancient Bahamut²',
    archetype: 'dragon',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#1e1b4b',
    secondaryColor: '#312e81',
    accentColor: '#60a5fa',
    coreGlow: '#93c5fd',
    eyeColor: '#fde047',
    pattern: 'draconic',
    headDetail: 'dragon-crest',
    specialAura: 'Dragon King Crown',
    description: 'Colossal king of all dragons, breathing celestial plasma and wearing sapphire royal scales.',
  },
  {
    id: 'dragon-secret-orochi',
    name: '★ OROCHI ELDER WYRM ★',
    archetype: 'dragon',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#ffffff',
    secondaryColor: '#e0e7ff',
    accentColor: '#e11d48',
    coreGlow: '#f43f5e',
    eyeColor: '#facc15',
    pattern: 'rainbow',
    headDetail: 'dragon-crest',
    specialAura: 'Mythological Aura Blast',
    description: 'ULTRA SECRET: The primordial eight-headed legendary wyrm reincarnated with pearlescent scales.',
  },

  // ==========================================
  // 6. CYBER ARCHETYPE
  // ==========================================
  {
    id: 'cyber-viper',
    name: 'Cyber Viper²',
    archetype: 'cyber',
    rarity: 'common',
    badge: 'CYBER',
    price: 0,
    primaryColor: '#06b6d4',
    secondaryColor: '#0e7490',
    accentColor: '#22d3ee',
    coreGlow: '#67e8f9',
    eyeColor: '#a5f3fc',
    pattern: 'cyber',
    headDetail: 'optic-sensor',
    specialAura: 'Cyan Grid Trail',
    description: 'Standard issue high-tech combat frame with reactive square armor tiles.',
  },
  {
    id: 'acid-matrix',
    name: 'Acid Matrix²',
    archetype: 'cyber',
    rarity: 'uncommon',
    badge: 'STEALTH',
    price: 2500,
    primaryColor: '#22c55e',
    secondaryColor: '#15803d',
    accentColor: '#4ade80',
    coreGlow: '#86efac',
    eyeColor: '#d9f99d',
    pattern: 'matrix',
    headDetail: 'visor',
    specialAura: 'Binary Cascade Wave',
    description: 'Encrypted digital warrior loaded with glowing binary data streams.',
  },
  {
    id: 'crimson-dread',
    name: 'Crimson Dread²',
    archetype: 'cyber',
    rarity: 'epic',
    badge: 'ASSAULT',
    price: 12000,
    primaryColor: '#ef4444',
    secondaryColor: '#991b1b',
    accentColor: '#f87171',
    coreGlow: '#fca5a5',
    eyeColor: '#fef08a',
    pattern: 'plasma',
    headDetail: 'dual-cannon',
    specialAura: 'Thermal Heat Dispersion',
    description: 'Heavy assault chassis with heat-sink vents and blazing thermal scales.',
  },
  {
    id: 'solar-destroyer',
    name: 'Solar Destroyer²',
    archetype: 'cyber',
    rarity: 'legendary',
    badge: 'SOLAR',
    price: 35000,
    primaryColor: '#f97316',
    secondaryColor: '#c2410c',
    accentColor: '#fb923c',
    coreGlow: '#fde047',
    eyeColor: '#ffffff',
    pattern: 'plasma',
    headDetail: 'dual-cannon',
    specialAura: 'Thermonuclear Reactor Flare',
    description: 'Thermonuclear fusion engine core emitting blinding solar flares.',
  },
  {
    id: 'cyber-hyperdrive',
    name: 'Hyperdrive Synthwave²',
    archetype: 'cyber',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#d946ef',
    secondaryColor: '#701a75',
    accentColor: '#06b6d4',
    coreGlow: '#f0abfc',
    eyeColor: '#22d3ee',
    pattern: 'neon',
    headDetail: 'optic-sensor',
    specialAura: 'Synthwave Horizon Grid',
    description: 'Neon synthwave cyberframe slicing through cyberspace at relativistic clock cycles.',
  },
  {
    id: 'cyber-secret-override',
    name: '★ SYSTEM OVERRIDE 404 ★',
    archetype: 'cyber',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#020617',
    secondaryColor: '#22c55e',
    accentColor: '#ef4444',
    coreGlow: '#38bdf8',
    eyeColor: '#fde047',
    pattern: 'glitch',
    headDetail: 'visor',
    specialAura: 'Kernel Panic Matrix',
    description: 'ULTRA SECRET: Corrupted zero-day exploit snake that bends canvas rendering into fractured glitch vectors.',
  },

  // ==========================================
  // 7. PHOENIX ARCHETYPE
  // ==========================================
  {
    id: 'phoenix-ash',
    name: 'Ash Fledgling²',
    archetype: 'phoenix',
    rarity: 'common',
    badge: 'ASH',
    price: 800,
    primaryColor: '#78350f',
    secondaryColor: '#451a03',
    accentColor: '#d97706',
    coreGlow: '#f59e0b',
    eyeColor: '#fef08a',
    pattern: 'phoenix',
    headDetail: 'phoenix-crest',
    specialAura: 'Warm Ash Embers',
    description: 'Young phoenix hatched from cinder pits, leaving a faint warm ember trail.',
  },
  {
    id: 'phoenix-firebird',
    name: 'Crimson Firebird²',
    archetype: 'phoenix',
    rarity: 'uncommon',
    badge: 'FIREBIRD',
    price: 2500,
    primaryColor: '#b91c1c',
    secondaryColor: '#7f1d1d',
    accentColor: '#f97316',
    coreGlow: '#fca5a5',
    eyeColor: '#fde047',
    pattern: 'phoenix',
    headDetail: 'phoenix-crest',
    specialAura: 'Blazing Wing Feathers',
    description: 'Majestic firebird whose fiery feathers ignite in the wind when hunting enemies.',
  },
  {
    id: 'phoenix-prime',
    name: 'Solar Phoenix²',
    archetype: 'phoenix',
    rarity: 'epic',
    badge: 'REBIRTH',
    price: 12000,
    primaryColor: '#ea580c',
    secondaryColor: '#7c2d12',
    accentColor: '#facc15',
    coreGlow: '#fed7aa',
    eyeColor: '#fef08a',
    pattern: 'phoenix',
    headDetail: 'phoenix-crest',
    specialAura: 'Phoenix Flame Wings',
    description: 'Immortal avian chassis that leaves a burning fire trail and revives once per match with an incandescent burst.',
  },
  {
    id: 'phoenix-supernova',
    name: 'Supernova Phoenix²',
    archetype: 'phoenix',
    rarity: 'legendary',
    badge: 'SOLAR',
    price: 35000,
    primaryColor: '#f59e0b',
    secondaryColor: '#b45309',
    accentColor: '#ef4444',
    coreGlow: '#fef08a',
    eyeColor: '#ffffff',
    pattern: 'phoenix',
    headDetail: 'phoenix-crest',
    specialAura: 'Corona Solar Flare',
    description: 'Blazing phoenix reborn in stellar core explosions, radiant with pure thermonuclear fire.',
  },
  {
    id: 'phoenix-sun-god',
    name: 'Eternal Ra Sovereign²',
    archetype: 'phoenix',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#facc15',
    secondaryColor: '#ca8a04',
    accentColor: '#e11d48',
    coreGlow: '#fef9c3',
    eyeColor: '#38bdf8',
    pattern: 'phoenix',
    headDetail: 'phoenix-crest',
    specialAura: 'Eternal Sun Disc',
    description: 'Solar deity serpent crowned with divine sun disc and incandescent white-gold wings.',
  },
  {
    id: 'phoenix-secret-rebirth',
    name: '★ PRIMORDIAL INFERNO ★',
    archetype: 'phoenix',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#ffffff',
    secondaryColor: '#ea580c',
    accentColor: '#f43f5e',
    coreGlow: '#fbbf24',
    eyeColor: '#22d3ee',
    pattern: 'rainbow',
    headDetail: 'phoenix-crest',
    specialAura: 'Rainbow Solar Core',
    description: 'ULTRA SECRET: The original spark of creation fire, blazing with infinite prismatic solar plumes.',
  },

  // ==========================================
  // 8. FROST ARCHETYPE
  // ==========================================
  {
    id: 'frost-snow',
    name: 'Snow Leopard Viper²',
    archetype: 'frost',
    rarity: 'common',
    badge: 'SNOW',
    price: 800,
    primaryColor: '#94a3b8',
    secondaryColor: '#64748b',
    accentColor: '#cbd5e1',
    coreGlow: '#f1f5f9',
    eyeColor: '#38bdf8',
    pattern: 'frost',
    headDetail: 'frost-horns',
    specialAura: 'Frosted Breath',
    description: 'Arctic camouflage serpent blended with high-altitude snowfields and tundra.',
  },
  {
    id: 'frost-permafrost',
    name: 'Permafrost Viper²',
    archetype: 'frost',
    rarity: 'uncommon',
    badge: 'PERMAFROST',
    price: 2500,
    primaryColor: '#0369a1',
    secondaryColor: '#075985',
    accentColor: '#38bdf8',
    coreGlow: '#7dd3fc',
    eyeColor: '#e0f2fe',
    pattern: 'frost',
    headDetail: 'frost-horns',
    specialAura: 'Rime Crystal Spine',
    description: 'Ancient glacial predator frozen deep within permafrost, revived by arctic blizzards.',
  },
  {
    id: 'frost-wyrm',
    name: 'Glacial Frost²',
    archetype: 'frost',
    rarity: 'epic',
    badge: 'CRYO',
    price: 12000,
    primaryColor: '#0284c7',
    secondaryColor: '#082f49',
    accentColor: '#38bdf8',
    coreGlow: '#e0f2fe',
    eyeColor: '#67e8f9',
    pattern: 'frost',
    headDetail: 'frost-horns',
    specialAura: 'Crystalline Glaze',
    description: 'Cryogenic beast leaving a sub-zero rime ice trail that slows pursuers, stacking freeze on bullet impacts.',
  },
  {
    id: 'frost-leviathan',
    name: 'Absolute Zero Leviathan²',
    archetype: 'frost',
    rarity: 'legendary',
    badge: 'FROST',
    price: 35000,
    primaryColor: '#082f49',
    secondaryColor: '#0c4a6e',
    accentColor: '#67e8f9',
    coreGlow: '#cffafe',
    eyeColor: '#ffffff',
    pattern: 'frost',
    headDetail: 'frost-horns',
    specialAura: 'Absolute Zero Cloud',
    description: 'Colossal arctic titan chilling surrounding air down to 0 Kelvin, crystallizing all motion.',
  },
  {
    id: 'frost-empress',
    name: 'Blizzard Empress²',
    archetype: 'frost',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#e0f2fe',
    secondaryColor: '#0284c7',
    accentColor: '#38bdf8',
    coreGlow: '#ffffff',
    eyeColor: '#0284c7',
    pattern: 'frost',
    headDetail: 'frost-horns',
    specialAura: 'Aurora Borealis Curtain',
    description: 'Sovereign of the north pole adorned in shimmering diamond frost crowns and northern lights.',
  },
  {
    id: 'frost-secret-singularity',
    name: '★ CRYO SINGULARITY ★',
    archetype: 'frost',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#ffffff',
    secondaryColor: '#38bdf8',
    accentColor: '#ec4899',
    coreGlow: '#cffafe',
    eyeColor: '#06b6d4',
    pattern: 'rainbow',
    headDetail: 'frost-horns',
    specialAura: 'Prismatic Diamond Glaze',
    description: 'ULTRA SECRET: Supercooled crystal anomaly refracting ambient light into dazzling sub-zero spectra.',
  },

  // ==========================================
  // 9. VENOM ARCHETYPE
  // ==========================================
  {
    id: 'venom-adder',
    name: 'Swamp Adder²',
    archetype: 'venom',
    rarity: 'common',
    badge: 'SWAMP',
    price: 800,
    primaryColor: '#3f6212',
    secondaryColor: '#365314',
    accentColor: '#65a30d',
    coreGlow: '#bef264',
    eyeColor: '#facc15',
    pattern: 'venom',
    headDetail: 'venom-fangs',
    specialAura: 'Bog Miasma',
    description: 'Murky swamp stalker tipped with toxic barbs suited for ambush warfare in murky shallows.',
  },
  {
    id: 'venom-python',
    name: 'Blight Python²',
    archetype: 'venom',
    rarity: 'uncommon',
    badge: 'BLIGHT',
    price: 2500,
    primaryColor: '#166534',
    secondaryColor: '#14532d',
    accentColor: '#4ade80',
    coreGlow: '#86efac',
    eyeColor: '#ef4444',
    pattern: 'venom',
    headDetail: 'venom-fangs',
    specialAura: 'Corrosive Slime',
    description: 'Mutated forest serpent exuding acidic secretions that decay armor upon touch.',
  },
  {
    id: 'venom-viper',
    name: 'Toxic Venom²',
    archetype: 'venom',
    rarity: 'epic',
    badge: 'TOXIC',
    price: 12000,
    primaryColor: '#65a30d',
    secondaryColor: '#14532d',
    accentColor: '#a3e635',
    coreGlow: '#d9f99d',
    eyeColor: '#bef264',
    pattern: 'venom',
    headDetail: 'venom-fangs',
    specialAura: 'Neurotoxin Miasma',
    description: 'Noxious serpent whose bullets deal lethal damage over time (DoT) while leaving a toxic ground trail.',
  },
  {
    id: 'venom-cobra-king',
    name: 'Venomous Cobra King²',
    archetype: 'venom',
    rarity: 'legendary',
    badge: 'COBRA',
    price: 35000,
    primaryColor: '#4d7c0f',
    secondaryColor: '#1a2e05',
    accentColor: '#84cc16',
    coreGlow: '#ecfccb',
    eyeColor: '#fde047',
    pattern: 'venom',
    headDetail: 'venom-fangs',
    specialAura: 'Royal Cobra Hood',
    description: 'Monarch of the toxic wastes featuring expanded venom glands and serrated acidic fangs.',
  },
  {
    id: 'venom-basilisk',
    name: 'Radioactive Basilisk²',
    archetype: 'venom',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#84cc16',
    secondaryColor: '#022c22',
    accentColor: '#eab308',
    coreGlow: '#a3e635',
    eyeColor: '#ef4444',
    pattern: 'venom',
    headDetail: 'venom-fangs',
    specialAura: 'Radiation Fallout Fog',
    description: 'Extremely hazardous radioactive mutation that corrupts enemy hull plating from afar.',
  },
  {
    id: 'venom-secret-hazard',
    name: '★ TOXIC HAZARD PROTOCOL ★',
    archetype: 'venom',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#022c22',
    secondaryColor: '#84cc16',
    accentColor: '#e11d48',
    coreGlow: '#a3e635',
    eyeColor: '#fbbf24',
    pattern: 'glitch',
    headDetail: 'venom-fangs',
    specialAura: 'Biohazard Level 5 Alarm',
    description: 'ULTRA SECRET: Synthesized bioweapon serpent pulsing with warning hazard hazard chevrons.',
  },

  // ==========================================
  // 10. STORM ARCHETYPE
  // ==========================================
  {
    id: 'storm-spark',
    name: 'Static Sparker²',
    archetype: 'storm',
    rarity: 'common',
    badge: 'SPARK',
    price: 800,
    primaryColor: '#475569',
    secondaryColor: '#334155',
    accentColor: '#60a5fa',
    coreGlow: '#93c5fd',
    eyeColor: '#38bdf8',
    pattern: 'storm',
    headDetail: 'storm-conductor',
    specialAura: 'Static Crackle',
    description: 'Lightweight electrical skirmisher gathering friction static to deliver snappy zaps.',
  },
  {
    id: 'storm-adder',
    name: 'Thunderstrike Adder²',
    archetype: 'storm',
    rarity: 'uncommon',
    badge: 'STRIKE',
    price: 2500,
    primaryColor: '#1d4ed8',
    secondaryColor: '#1e3a8a',
    accentColor: '#93c5fd',
    coreGlow: '#bfdbfe',
    eyeColor: '#facc15',
    pattern: 'storm',
    headDetail: 'storm-conductor',
    specialAura: 'Thunderhead Spark',
    description: 'Charged storm predator whose body vibrates in harmony with lightning strikes.',
  },
  {
    id: 'storm-breaker',
    name: 'Volt Storm²',
    archetype: 'storm',
    rarity: 'epic',
    badge: 'VOLT',
    price: 12000,
    primaryColor: '#2563eb',
    secondaryColor: '#172554',
    accentColor: '#60a5fa',
    coreGlow: '#dbeafe',
    eyeColor: '#93c5fd',
    pattern: 'storm',
    headDetail: 'storm-conductor',
    specialAura: 'Plasma Arc Generator',
    description: 'Thunderous battle-frame firing chain lightning that arcs across nearby enemies, with static shock boosting.',
  },
  {
    id: 'storm-raijin',
    name: 'Tempest Raijin²',
    archetype: 'storm',
    rarity: 'legendary',
    badge: 'RAIJIN',
    price: 35000,
    primaryColor: '#1e40af',
    secondaryColor: '#0f172a',
    accentColor: '#facc15',
    coreGlow: '#fef08a',
    eyeColor: '#ffffff',
    pattern: 'storm',
    headDetail: 'storm-conductor',
    specialAura: 'Thunder God Ward',
    description: 'Mythical storm deity armed with golden lightning conductor crests and thunderous aura.',
  },
  {
    id: 'storm-maelstrom',
    name: 'Cataclysmic Maelstrom²',
    archetype: 'storm',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#312e81',
    secondaryColor: '#1e1b4b',
    accentColor: '#38bdf8',
    coreGlow: '#7dd3fc',
    eyeColor: '#f43f5e',
    pattern: 'storm',
    headDetail: 'storm-conductor',
    specialAura: 'Supercell Hurricane',
    description: 'Unstoppable hurricane titan enveloped in a rotating dome of lightning and high winds.',
  },
  {
    id: 'storm-secret-overload',
    name: '★ 100,000 VOLTS OVERLOAD ★',
    archetype: 'storm',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#ffffff',
    secondaryColor: '#0284c7',
    accentColor: '#facc15',
    coreGlow: '#38bdf8',
    eyeColor: '#ef4444',
    pattern: 'rainbow',
    headDetail: 'storm-conductor',
    specialAura: 'Hyper-Voltage Superconduct',
    description: 'ULTRA SECRET: Pure superconducting plasma frame radiating blinding arc flashes that shatter the dark.',
  },

  // ==========================================
  // 11. PHANTOM ARCHETYPE
  // ==========================================
  {
    id: 'phantom-mist',
    name: 'Mist Spectre²',
    archetype: 'phantom',
    rarity: 'common',
    badge: 'MIST',
    price: 800,
    primaryColor: '#64748b',
    secondaryColor: '#475569',
    accentColor: '#94a3b8',
    coreGlow: '#cbd5e1',
    eyeColor: '#a5b4fc',
    pattern: 'phantom',
    headDetail: 'phantom-cowl',
    specialAura: 'Ghostly Vapour',
    description: 'Semi-corporeal shade hovering just above ground level, drifting unseen through smog.',
  },
  {
    id: 'phantom-nomad',
    name: 'Astral Nomad²',
    archetype: 'phantom',
    rarity: 'uncommon',
    badge: 'ASTRAL',
    price: 2500,
    primaryColor: '#4338ca',
    secondaryColor: '#312e81',
    accentColor: '#818cf8',
    coreGlow: '#c7d2fe',
    eyeColor: '#38bdf8',
    pattern: 'phantom',
    headDetail: 'phantom-cowl',
    specialAura: 'Astral Warp Dust',
    description: 'Interdimensional wanderer that slides between parallel folds of cyberspace.',
  },
  {
    id: 'phantom-spectre',
    name: 'Shadow Phantom²',
    archetype: 'phantom',
    rarity: 'epic',
    badge: 'PHASE',
    price: 12000,
    primaryColor: '#4f46e5',
    secondaryColor: '#1e1b4b',
    accentColor: '#818cf8',
    coreGlow: '#e0e7ff',
    eyeColor: '#c7d2fe',
    pattern: 'phantom',
    headDetail: 'phantom-cowl',
    specialAura: 'Spectral Rift Cloak',
    description: 'Translucent apparition that can phase through solid obstacles and barriers with quantum intangibility.',
  },
  {
    id: 'phantom-wraith',
    name: 'Netherworld Wraith²',
    archetype: 'phantom',
    rarity: 'legendary',
    badge: 'WRAITH',
    price: 35000,
    primaryColor: '#312e81',
    secondaryColor: '#09090b',
    accentColor: '#a855f7',
    coreGlow: '#e9d5ff',
    eyeColor: '#22d3ee',
    pattern: 'phantom',
    headDetail: 'phantom-cowl',
    specialAura: 'Soul Siphon Vortex',
    description: 'Terrifying ghostly horror that drinks fear, drifting unaffected through solid steel bunkers.',
  },
  {
    id: 'phantom-void-lord',
    name: 'Lord of the Void²',
    archetype: 'phantom',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#030712',
    secondaryColor: '#1e1b4b',
    accentColor: '#c084fc',
    coreGlow: '#e9d5ff',
    eyeColor: '#f43f5e',
    pattern: 'phantom',
    headDetail: 'phantom-cowl',
    specialAura: 'Eternal Nether Realm',
    description: 'Ancient phantom king commanding departed souls, flickering effortlessly in and out of reality.',
  },
  {
    id: 'phantom-secret-anomaly',
    name: '★ DIMENSIONAL ANOMALY ★',
    archetype: 'phantom',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#000000',
    secondaryColor: '#4f46e5',
    accentColor: '#06b6d4',
    coreGlow: '#a855f7',
    eyeColor: '#ffffff',
    pattern: 'glitch',
    headDetail: 'phantom-cowl',
    specialAura: 'Tesseract Phasing Field',
    description: 'ULTRA SECRET: A 4-dimensional glitch entity slicing reality into multiple non-Euclidean slices.',
  },

  // ==========================================
  // 12. VAMPIRE ARCHETYPE
  // ==========================================
  {
    id: 'vampire-stalker',
    name: 'Night Stalker²',
    archetype: 'vampire',
    rarity: 'common',
    badge: 'STALKER',
    price: 800,
    primaryColor: '#3f3f46',
    secondaryColor: '#27272a',
    accentColor: '#71717a',
    coreGlow: '#ef4444',
    eyeColor: '#dc2626',
    pattern: 'vampire',
    headDetail: 'vampire-fangs',
    specialAura: 'Shadow Prowl',
    description: 'Nocturnal scavenger lurking in the peripheral shadows, thirsting for warm life essence.',
  },
  {
    id: 'vampire-bat',
    name: 'Sanguine Bat²',
    archetype: 'vampire',
    rarity: 'uncommon',
    badge: 'BAT',
    price: 2500,
    primaryColor: '#7f1d1d',
    secondaryColor: '#450a0a',
    accentColor: '#dc2626',
    coreGlow: '#f87171',
    eyeColor: '#facc15',
    pattern: 'vampire',
    headDetail: 'vampire-fangs',
    specialAura: 'Bat Wing Flight',
    description: 'Winged vampire with acute echolocation and blood-scenting sensory antennas.',
  },
  {
    id: 'vampire-lord',
    name: 'Crimson Vampire²',
    archetype: 'vampire',
    rarity: 'epic',
    badge: 'BLOOD',
    price: 12000,
    primaryColor: '#991b1b',
    secondaryColor: '#18181b',
    accentColor: '#ef4444',
    coreGlow: '#fecaca',
    eyeColor: '#dc2626',
    pattern: 'vampire',
    headDetail: 'vampire-fangs',
    specialAura: 'Crimson Blood Mist',
    description: 'Nocturnal dread chassis siphoning massive life upon kills, bursting with a swarming bat death effect.',
  },
  {
    id: 'vampire-nosferatu',
    name: 'Nosferatu Bloodlord²',
    archetype: 'vampire',
    rarity: 'legendary',
    badge: 'BLOODLORD',
    price: 35000,
    primaryColor: '#18181b',
    secondaryColor: '#7f1d1d',
    accentColor: '#b91c1c',
    coreGlow: '#ef4444',
    eyeColor: '#fca5a5',
    pattern: 'vampire',
    headDetail: 'vampire-fangs',
    specialAura: 'Blood Feast Mist',
    description: 'Ancient gothic predator with elongated ivory fangs and an insatiable hunger for biomass.',
  },
  {
    id: 'vampire-dracula',
    name: 'Dracula Sovereign²',
    archetype: 'vampire',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#450a0a',
    secondaryColor: '#09090b',
    accentColor: '#fbbf24',
    coreGlow: '#fca5a5',
    eyeColor: '#ef4444',
    pattern: 'vampire',
    headDetail: 'vampire-fangs',
    specialAura: 'Royal Crimson Court',
    description: 'High progenitor of the bloodline draped in velvet crimson cloak and regal gold accents.',
  },
  {
    id: 'vampire-secret-eclipse',
    name: '★ CRIMSON ECLIPSE ★',
    archetype: 'vampire',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#000000',
    secondaryColor: '#991b1b',
    accentColor: '#ec4899',
    coreGlow: '#f43f5e',
    eyeColor: '#ffffff',
    pattern: 'glitch',
    headDetail: 'vampire-fangs',
    specialAura: 'Total Blood Moon Eclipse',
    description: 'ULTRA SECRET: Awakens under the blood moon, dripping dark crimson plasma that dissolves the arena.',
  },

  // ==========================================
  // 13. CHRONO ARCHETYPE
  // ==========================================
  {
    id: 'chrono-tinker',
    name: 'Clockwork Tinkerer²',
    archetype: 'chrono',
    rarity: 'common',
    badge: 'TINKER',
    price: 800,
    primaryColor: '#78350f',
    secondaryColor: '#451a03',
    accentColor: '#b45309',
    coreGlow: '#fde68a',
    eyeColor: '#f59e0b',
    pattern: 'chrono',
    headDetail: 'chrono-gear',
    specialAura: 'Brass Cog Tick',
    description: 'Hand-crafted automaton assembled from antique brass watch gears and copper springs.',
  },
  {
    id: 'chrono-hourglass',
    name: 'Hourglass Serpent²',
    archetype: 'chrono',
    rarity: 'uncommon',
    badge: 'HOURGLASS',
    price: 2500,
    primaryColor: '#d97706',
    secondaryColor: '#92400e',
    accentColor: '#fcd34d',
    coreGlow: '#fef3c7',
    eyeColor: '#38bdf8',
    pattern: 'chrono',
    headDetail: 'chrono-gear',
    specialAura: 'Time Sand Sift',
    description: 'Serpent whose translucent segments reveal fine temporal sand trickling backward in time.',
  },
  {
    id: 'chrono-weaver',
    name: 'Temporal Chrono²',
    archetype: 'chrono',
    rarity: 'epic',
    badge: 'TIME',
    price: 12000,
    primaryColor: '#b45309',
    secondaryColor: '#451a03',
    accentColor: '#f59e0b',
    coreGlow: '#fef3c7',
    eyeColor: '#fde68a',
    pattern: 'chrono',
    headDetail: 'chrono-gear',
    specialAura: 'Clockwork Gears Field',
    description: 'Temporal warden manipulating spacetime with a localized time-slow bubble and rotating gear visuals.',
  },
  {
    id: 'chrono-paradox',
    name: 'Chrono Paradox Master²',
    archetype: 'chrono',
    rarity: 'legendary',
    badge: 'PARADOX',
    price: 35000,
    primaryColor: '#d97706',
    secondaryColor: '#172554',
    accentColor: '#38bdf8',
    coreGlow: '#fde68a',
    eyeColor: '#ffffff',
    pattern: 'chrono',
    headDetail: 'chrono-gear',
    specialAura: 'Spacetime Tachyon Arc',
    description: 'Master of temporal paradoxes, reversing entropy and moving through past and future states.',
  },
  {
    id: 'chrono-aeon',
    name: 'Infinite Aeon Weaver²',
    archetype: 'chrono',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#1e1b4b',
    secondaryColor: '#b45309',
    accentColor: '#facc15',
    coreGlow: '#fef08a',
    eyeColor: '#38bdf8',
    pattern: 'chrono',
    headDetail: 'chrono-gear',
    specialAura: 'Aeon Chronometer Sphere',
    description: 'Cosmic clockmaker maintaining the rhythm of universal spacetime across infinite dimensions.',
  },
  {
    id: 'chrono-secret-zero',
    name: '★ TIME COLLAPSE: 00:00:00 ★',
    archetype: 'chrono',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#000000',
    secondaryColor: '#f59e0b',
    accentColor: '#06b6d4',
    coreGlow: '#fbbf24',
    eyeColor: '#e11d48',
    pattern: 'glitch',
    headDetail: 'chrono-gear',
    specialAura: 'Universal Stop Clock',
    description: 'ULTRA SECRET: The moment when the universe ceases to tick. Clock hands run backward in wild quantum spin.',
  },

  // ==========================================
  // 14. NINJA ARCHETYPE
  // ==========================================
  {
    id: 'ninja-genin',
    name: 'Genin Recruit²',
    archetype: 'ninja',
    rarity: 'common',
    badge: 'GENIN',
    price: 800,
    primaryColor: '#27272a',
    secondaryColor: '#18181b',
    accentColor: '#ef4444',
    coreGlow: '#52525b',
    eyeColor: '#f43f5e',
    pattern: 'ninja',
    headDetail: 'ninja-mask',
    specialAura: 'Shuriken Whir',
    description: 'Initiate shinobi clad in silent charcoal cloth, trained in basic blade maneuvers.',
  },
  {
    id: 'ninja-kunai',
    name: 'Kunai Shadow²',
    archetype: 'ninja',
    rarity: 'uncommon',
    badge: 'KUNAI',
    price: 2500,
    primaryColor: '#1e293b',
    secondaryColor: '#0f172a',
    accentColor: '#38bdf8',
    coreGlow: '#94a3b8',
    eyeColor: '#38bdf8',
    pattern: 'ninja',
    headDetail: 'ninja-mask',
    specialAura: 'Shadow Cloak Smoke',
    description: 'Covert infiltrator armed with balanced throwing daggers and midnight camouflage.',
  },
  {
    id: 'ninja-shadow',
    name: 'Shinobi Ninja²',
    archetype: 'ninja',
    rarity: 'epic',
    badge: 'SHADOW',
    price: 12000,
    primaryColor: '#18181b',
    secondaryColor: '#09090b',
    accentColor: '#ef4444',
    coreGlow: '#71717a',
    eyeColor: '#f43f5e',
    pattern: 'ninja',
    headDetail: 'ninja-mask',
    specialAura: 'Shadow Katana Gleam',
    description: 'Covert master replacing firearms with lethal katana dash-slash melee strikes and smoke bomb escapes.',
  },
  {
    id: 'ninja-hanzo',
    name: 'Jonin Hanzo²',
    archetype: 'ninja',
    rarity: 'legendary',
    badge: 'JONIN',
    price: 35000,
    primaryColor: '#09090b',
    secondaryColor: '#1c1917',
    accentColor: '#f59e0b',
    coreGlow: '#ef4444',
    eyeColor: '#ffffff',
    pattern: 'ninja',
    headDetail: 'ninja-mask',
    specialAura: 'Dragon Katana Wind',
    description: 'Legendary clan leader whose blades slash with the speed of thunder through enemy squads.',
  },
  {
    id: 'ninja-kage',
    name: 'Kage Grandmaster²',
    archetype: 'ninja',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#f8fafc',
    secondaryColor: '#0f172a',
    accentColor: '#f43f5e',
    coreGlow: '#ffffff',
    eyeColor: '#facc15',
    pattern: 'ninja',
    headDetail: 'ninja-mask',
    specialAura: 'White Lotus Smoke',
    description: 'Supreme grandmaster draped in ceremonial white silk, slicing dimensions with unmatched precision.',
  },
  {
    id: 'ninja-secret-muramasa',
    name: '★ MURAMASA BLOOD BLADE ★',
    archetype: 'ninja',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#000000',
    secondaryColor: '#e11d48',
    accentColor: '#facc15',
    coreGlow: '#fb7185',
    eyeColor: '#38bdf8',
    pattern: 'glitch',
    headDetail: 'ninja-mask',
    specialAura: 'Cursed Blade Resonance',
    description: 'ULTRA SECRET: The forbidden demonic katana forged in underworld flames, trailing crimson phantom cuts.',
  },

  // ==========================================
  // 15. CRYSTAL ARCHETYPE
  // ==========================================
  {
    id: 'crystal-quartz',
    name: 'Quartz Shard²',
    archetype: 'crystal',
    rarity: 'common',
    badge: 'QUARTZ',
    price: 800,
    primaryColor: '#cbd5e1',
    secondaryColor: '#94a3b8',
    accentColor: '#e2e8f0',
    coreGlow: '#f8fafc',
    eyeColor: '#22d3ee',
    pattern: 'crystal',
    headDetail: 'crystal-facets',
    specialAura: 'Quartz Sparkle',
    description: 'Natural mineral frame of raw quartz geodes, deflecting stray shrapnel with stony density.',
  },
  {
    id: 'crystal-amethyst',
    name: 'Amethyst Viper²',
    archetype: 'crystal',
    rarity: 'uncommon',
    badge: 'AMETHYST',
    price: 2500,
    primaryColor: '#7e22ce',
    secondaryColor: '#581c87',
    accentColor: '#c084fc',
    coreGlow: '#e9d5ff',
    eyeColor: '#a855f7',
    pattern: 'crystal',
    headDetail: 'crystal-facets',
    specialAura: 'Amethyst Prisms',
    description: 'Deep royal purple crystal reptile with sharp geometric mineral plates.',
  },
  {
    id: 'crystal-golem',
    name: 'Prismatic Crystal²',
    archetype: 'crystal',
    rarity: 'epic',
    badge: 'TANK',
    price: 12000,
    primaryColor: '#0891b2',
    secondaryColor: '#164e63',
    accentColor: '#22d3ee',
    coreGlow: '#cffafe',
    eyeColor: '#67e8f9',
    pattern: 'crystal',
    headDetail: 'crystal-facets',
    specialAura: 'Prismatic Refraction Gleam',
    description: 'Heavy armored crystal tank with fortified hitpoints and prismatic facets that reflect enemy bullets.',
  },
  {
    id: 'crystal-diamond',
    name: 'Obsidian Diamond Behemoth²',
    archetype: 'crystal',
    rarity: 'legendary',
    badge: 'DIAMOND',
    price: 35000,
    primaryColor: '#164e63',
    secondaryColor: '#083344',
    accentColor: '#67e8f9',
    coreGlow: '#e0f2fe',
    eyeColor: '#ffffff',
    pattern: 'crystal',
    headDetail: 'crystal-facets',
    specialAura: 'Diamond Hardened Hull',
    description: 'Diamond-density monolith virtually immune to kinetic impacts, reflecting projectiles like a mirror.',
  },
  {
    id: 'crystal-cosmos',
    name: 'Prism of the Cosmos²',
    archetype: 'crystal',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#06b6d4',
    secondaryColor: '#701a75',
    accentColor: '#f472b6',
    coreGlow: '#cffafe',
    eyeColor: '#facc15',
    pattern: 'crystal',
    headDetail: 'crystal-facets',
    specialAura: 'Cosmic Light Refractor',
    description: 'Intergalactic crystal prism splitting starlight into defensive electromagnetic force shields.',
  },
  {
    id: 'crystal-secret-philosopher',
    name: "★ PHILOSOPHER'S STONE ★",
    archetype: 'crystal',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#dc2626',
    secondaryColor: '#eab308',
    accentColor: '#f43f5e',
    coreGlow: '#fef08a',
    eyeColor: '#38bdf8',
    pattern: 'rainbow',
    headDetail: 'crystal-facets',
    specialAura: 'Alchemical Transmutation',
    description: 'ULTRA SECRET: The legendary red alchemical stone turning base metal into pure gold and immortality.',
  },

  // ==========================================
  // 16. ALIEN ARCHETYPE
  // ==========================================
  {
    id: 'alien-spore',
    name: 'Spore Larva²',
    archetype: 'alien',
    rarity: 'common',
    badge: 'LARVA',
    price: 800,
    primaryColor: '#15803d',
    secondaryColor: '#14532d',
    accentColor: '#4ade80',
    coreGlow: '#86efac',
    eyeColor: '#bef264',
    pattern: 'alien',
    headDetail: 'alien-antennae',
    specialAura: 'Bioluminescent Pod',
    description: 'Juvenile extraterrestrial spawn emitting rhythmic bio-light pulses from cranial pods.',
  },
  {
    id: 'alien-parasite',
    name: 'Meteorite Parasite²',
    archetype: 'alien',
    rarity: 'uncommon',
    badge: 'PARASITE',
    price: 2500,
    primaryColor: '#581c87',
    secondaryColor: '#3b0764',
    accentColor: '#a855f7',
    coreGlow: '#84cc16',
    eyeColor: '#a3e635',
    pattern: 'alien',
    headDetail: 'alien-antennae',
    specialAura: 'Alien Spore Haze',
    description: 'Xenomorphic organism arriving in deep space meteorites, carrying caustic acidic bile.',
  },
  {
    id: 'alien-xeno',
    name: 'Xenomorph Alien²',
    archetype: 'alien',
    rarity: 'epic',
    badge: 'BIO',
    price: 12000,
    primaryColor: '#059669',
    secondaryColor: '#022c22',
    accentColor: '#10b981',
    coreGlow: '#6ee7b7',
    eyeColor: '#a7f3d0',
    pattern: 'alien',
    headDetail: 'alien-antennae',
    specialAura: 'Bio-Luminescent Pulse',
    description: 'Extraterrestrial predator spewing acid spit that completely dissolves shields, wrapped in a glowing bio-luminescent body.',
  },
  {
    id: 'alien-hivemind',
    name: 'Hive Mind Sovereign²',
    archetype: 'alien',
    rarity: 'legendary',
    badge: 'HIVEMIND',
    price: 35000,
    primaryColor: '#064e3b',
    secondaryColor: '#022c22',
    accentColor: '#34d399',
    coreGlow: '#6ee7b7',
    eyeColor: '#facc15',
    pattern: 'alien',
    headDetail: 'alien-antennae',
    specialAura: 'Psionic Hive Signal',
    description: 'Central telepathic commander of the swarm, coordinating synchronized acid spit barrages.',
  },
  {
    id: 'alien-leviathan',
    name: 'Ancient Cosmic Leviathan²',
    archetype: 'alien',
    rarity: 'mythic',
    badge: 'MYTHIC',
    price: 65000,
    primaryColor: '#1e1b4b',
    secondaryColor: '#0f172a',
    accentColor: '#10b981',
    coreGlow: '#34d399',
    eyeColor: '#f43f5e',
    pattern: 'alien',
    headDetail: 'alien-antennae',
    specialAura: 'Deep Space Bioluminescence',
    description: 'Colossal void creature swimming through vacuum, pulsing with psychedelic alien frequencies.',
  },
  {
    id: 'alien-secret-specimen',
    name: '★ AREA 51: SPECIMEN ZERO ★',
    archetype: 'alien',
    rarity: 'secret',
    badge: '★ SECRET ★',
    price: 150000,
    crateExclusive: true,
    primaryColor: '#000000',
    secondaryColor: '#84cc16',
    accentColor: '#ec4899',
    coreGlow: '#a3e635',
    eyeColor: '#38bdf8',
    pattern: 'glitch',
    headDetail: 'alien-antennae',
    specialAura: 'Extraterrestrial Glyph Radiation',
    description: 'ULTRA SECRET: The classified lifeform kept in cryogenic containment. Acid tears through reality.',
  },
];

export function getSkinById(id: string): SkinDef {
  return SKINS.find((s) => s.id === id) || SKINS[0];
}

export function getSkinsByArchetype(archetype: SnakeArchetype): SkinDef[] {
  return SKINS.filter((s) => s.archetype === archetype);
}

export function getSkinsByRarity(rarity: SkinRarity): SkinDef[] {
  return SKINS.filter((s) => s.rarity === rarity);
}

export function rollSkinFromCrate(): { skin: SkinDef; isSecret: boolean } {
  // Transparent odds:
  // Secret: 0.8%
  // Mythic: 4.2%
  // Legendary: 8.5%
  // Epic: 18.0%
  // Uncommon: 28.5%
  // Common: 40.0%
  const rand = Math.random() * 100;
  let targetRarity: SkinRarity = 'common';

  if (rand < 0.8) {
    targetRarity = 'secret';
  } else if (rand < 0.8 + 4.2) {
    targetRarity = 'mythic';
  } else if (rand < 0.8 + 4.2 + 8.5) {
    targetRarity = 'legendary';
  } else if (rand < 0.8 + 4.2 + 8.5 + 18.0) {
    targetRarity = 'epic';
  } else if (rand < 0.8 + 4.2 + 8.5 + 18.0 + 28.5) {
    targetRarity = 'uncommon';
  } else {
    targetRarity = 'common';
  }

  const pool = SKINS.filter((s) => s.rarity === targetRarity);
  const selected = pool[Math.floor(Math.random() * pool.length)] || SKINS[0];
  return {
    skin: selected,
    isSecret: selected.rarity === 'secret',
  };
}
