import { TrailDef, TrailType } from '../types';

export type { TrailDef, TrailType };

export const TRAILS: TrailDef[] = [
  {
    id: 'none',
    name: 'Standard Exhaust',
    price: 0,
    description: 'Factory-standard micro-thrust particle wake.',
    badge: 'DEFAULT',
    rarity: 'Common',
    color: '#64748b',
    primaryColor: '#64748b',
    glowColor: 'rgba(100, 116, 139, 0.4)',
    previewGradient: 'from-slate-700 to-slate-900',
    icon: '💨',
  },
  {
    id: 'matrix',
    name: 'Matrix Digital Rain',
    price: 1200,
    description: 'Cascading holographic neon green binary code glyphs stream from your tail.',
    badge: 'CYBER',
    rarity: 'Rare',
    color: '#22c55e',
    primaryColor: '#22c55e',
    glowColor: '#4ade80',
    previewGradient: 'from-emerald-500 to-green-900',
    icon: '💻',
  },
  {
    id: 'lightning',
    name: 'Plasma Lightning',
    price: 1800,
    description: 'High-voltage electric arcs and cyan plasma sparks snapping in your wake.',
    badge: 'ENERGY',
    rarity: 'Epic',
    color: '#06b6d4',
    primaryColor: '#06b6d4',
    glowColor: '#38bdf8',
    previewGradient: 'from-cyan-400 to-blue-900',
    icon: '⚡',
  },
  {
    id: 'rainbow',
    name: 'Vaporwave Rainbow',
    price: 2400,
    description: 'Prismatic chromatic gradient trail cycling through synthwave neon colors.',
    badge: 'VAPOR',
    rarity: 'Legendary',
    color: '#f43f5e',
    primaryColor: '#f43f5e',
    glowColor: '#a855f7',
    previewGradient: 'from-pink-500 via-purple-500 to-cyan-500',
    icon: '🌈',
  },
  {
    id: 'fire',
    name: 'Inferno Afterburner',
    price: 2200,
    description: 'Blazing rocket exhaust with flying orange embers and white-hot ignition core.',
    badge: 'FLAME',
    rarity: 'Epic',
    color: '#f97316',
    primaryColor: '#f97316',
    glowColor: '#ef4444',
    previewGradient: 'from-amber-500 to-rose-900',
    icon: '🔥',
  },
  {
    id: 'bubbles',
    name: 'Neon Cyber Bubbles',
    price: 1500,
    description: 'Translucent glowing bio-luminescent orbs that pop with energetic sparkle rings.',
    badge: 'AQUA',
    rarity: 'Rare',
    color: '#3b82f6',
    primaryColor: '#3b82f6',
    glowColor: '#60a5fa',
    previewGradient: 'from-blue-400 to-sky-900',
    icon: '🫧',
  },
  {
    id: 'stardust',
    name: 'Cosmic Stardust',
    price: 3000,
    description: 'Radiant 4-pointed galactic stars and golden celestial stardust glimmering in space.',
    badge: 'MYTHIC',
    rarity: 'Mythic',
    color: '#eab308',
    primaryColor: '#eab308',
    glowColor: '#c084fc',
    previewGradient: 'from-yellow-400 via-amber-500 to-purple-900',
    icon: '✨',
  },
];

export function getTrailById(id?: TrailType): TrailDef {
  return TRAILS.find((t) => t.id === id) || TRAILS[0];
}
